name: invoices
version: 0.0.0
license: MIT
copyright: "2022 Carlos Prado"
github: "cpradog/invoices"
author: "Carlos Prado <carlos.prado@cpradog.com>"
maintainer: "carlos.prado@cpradog.com"
description: "Please see the README on GitHub at <https://github.com/githubuser/invoices#readme>"
synopsis: "Plain text invoice manager"
category: Finances

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - hspec
  - hspec-contrib

library:
  source-dirs: src

executables:
  invoices-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - invoices

tests:
  invoices-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - invoices
