name: release

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Tests pass
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache stack
        uses: actions/cache@v2
        env:
          cache-name: cache-stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: setup haskell environment
        uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-setup-ghc: true

      - name: run tests
        run: make test

  release:
    name: Publish new release
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache stack
        uses: actions/cache@v2
        env:
          cache-name: cache-stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: setup haskell environment
        uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-setup-ghc: true

      - name: calculate new version
        id: version
        uses: cpradog/cicd-actions/version-bump@master

      - name: update package version
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: "package.yaml"
          propertyPath: "version"
          value: ${{ steps.version.outputs.version }}
          updateFile: true
          commitChange: false

      - name: publish
        run: make publish

      - name: Github release
        uses: softprops/action-gh-release@v1
        with:
          name: "v${{ steps.version.outputs.version }}"
          tag_name: "v${{ steps.version.outputs.version }}"
          generate_release_notes: true
          files: dist-newstyle/sdist/*
